builder/BuildSoGiveApp.java
When calstat is included in dependencies, `java -jar bob-all.jar` fails for me with
```
#bob.WWDependencyTask Running WWDependencyTask[projectName=calstat] at Sat, 16 May 2020 19:02:04...                                                                                                                             
#bob.WWDependencyTask ...exiting WWDependencyTask[projectName=calstat]                            
#bob.BuildSoGiveApp ...exiting BuildSoGiveApp[projectName=sogive]                                                                                                                                                               
Exception in thread "main" java.lang.NullPointerException                                     
at com.winterwell.bob.tasks.EclipseClasspath.<init>(EclipseClasspath …
```
=> Remove calstat from BuildSoGiveApp dependencies

README.md
- I found ./convert.less.sh only worked from bash and if I installed node-less first, hence adding this to step 5.
- Tidied up formatting of command line instructions (they weren't previously formatted as code) and numbers in the markdown (removed duplicate).
=> Improve frontend installation instructions

src/js/components/DonationWizard.jsx
Simplest fix for Sanjay's request that we stop allowing monthly donations to a particular fundraiser - theses changes* stop letting users create repeating donations for all event fundraisers. 
*Well, the 2nd commit does; the 1st commit (hiding the checkbox) is actually rendered unnecessary by the 2nd, but might be useful in future if and when we reinstate repeating donations for event fundraisers.
=> Disallow repeating donations for event fundraisers

README.md
Added double-tab indentation to render commands in fixed-width font, and preserve linebreaks.
=> Render commands in README better

src/puppeteer-tests/testConfig.js
- Now tests can be run against the real site using `--site prod` flag
=> [Puppeteer tests] Fix typo in prod server config

runtest.js
- Previously, you could just filter by test file name using the
`-- test` option.
- Now you can also filter by test name, to run a subset of tests
within a file.
- Note, instructions for using this flag were already added to the
README (I didn't notice this didn't work with the runtest.js script at
the time).
- The `-- -t` syntax is because this is how it works if you run tests
via the `npm run test` method, and I think it makes sense to keep them
consistent.
=> [Puppeteer tests] Make tests filterable by name

.gitignore
This should allow me to develop faster in my preferred IDE while not accidentally committing IntelliJ-generated files
For the record, I could only get IntelliJ to import the project by importing it as a Maven project, *not* by importing it as an Eclipse project. But then it was possible to import the other projects as Eclipse modules (from Project Structure settings) & this worked better than attempting to import them as Maven modules.
=> Add IntelliJ-generated project files to .gitignore

.classpath, builder/BuildSoGiveApp.java, src/java/org/sogive/data/loader/DatabaseWriter.java, src/java/org/sogive/data/loader/Editorial.java, src/java/org/sogive/data/loader/Editorials.java, src/java/org/sogive/data/loader/EditorialsFetcher.java, src/java/org/sogive/data/loader/ElasticSearchDatabaseWriter.java, src/java/org/sogive/data/loader/ImportEditorialsDataTask.java, src/java/org/sogive/data/loader/JsoupDocumentFetcher.java, src/java/org/sogive/data/loader/JsoupDocumentFetcherImpl.java, src/java/org/sogive/server/ImportDataServlet.java, src/js/components/editor/EditorDashboardPage.jsx, src/js/plumbing/ServerIO.js, src/puppeteer-tests/__tests__/editor-dashboard.test.js, test/java/org/sogive/data/loader/FakeJsoupDocumentFetcher.java, test/java/org/sogive/data/loader/ImportEditorialsDataTaskTest.java
=> WIP: Upload editorials tool

src/java/org/sogive/data/loader/EditorialsFetcher.java, src/java/org/sogive/data/loader/ImportEditorialsDataTask.java, src/java/org/sogive/server/ImportDataServlet.java, src/js/components/editor/EditorDashboardPage.jsx, src/js/plumbing/ServerIO.js, src/puppeteer-tests/__tests__/editor-dashboard.test.js, test/java/org/sogive/data/loader/ImportEditorialsDataTaskTest.java
=> Fixes for the editorials importer tool

src/js/components/DonationWizard.jsx
This fixes the error seen after passing the GiftAid step in the donation wizard:
However, I still get the following error at the same step:
```
Uncaught Error: assert-failed: ["PaymentWidget.jsx a-match: undefined !~ undefined"]
at assertFailed (assert.js:41)
at assert (assert.js:30)
at assMatch (assert.js:61)
at PaymentWidget (PaymentWidget.jsx:80)
```
(I think probably related to what @roscoemcinerney was saying in the GoodLoop chat.)
At least this is a step in the right direction.
=> Fix money validation error in DonationWizard

src/java/org/sogive/data/DBSoGive.java
'tbd' is supposed to be a dummy charity that can stand in for a real charity for testing
While the handful of real charities I checked **all** had 'name' set, at least one ('The END Fund') did **not** have displayName set
Therefore it makes sense to make the dummy charity have this 'name' property instead of displayName
(Also, if 'name' is not set then the DonationWizard crashes. What do you think, should DonationWizard handle this edge case? Or do we expect 'name' to always be set? It could fallback to charity id, but for payments I don't know if that would be a valid recipient..)
=> Set 'name' not 'displayName' for dummy charity on startup

src/java/org/sogive/data/loader/DatabaseWriter.java, src/java/org/sogive/data/loader/ElasticSearchDatabaseWriter.java, src/java/org/sogive/data/loader/ImportEditorialsDataTask.java, test/java/org/sogive/data/loader/ImportEditorialsDataTaskTest.java
This commit makes the importer tool still import editorials for charities which are only in draft, without publishing them.
(This was a request from Sanjay / Gergo, since a lot of the new editorials are for charities which are not published yet).
=> Make the importer tool import draft editorials too

src/js/C.js, src/js/components/SearchPage.jsx, src/js/components/editor/SimpleEditCharityPage.jsx
Hello again, Sanjay requested this small change for analysts implementing the new rating system on Saturday. More context: https://docs.google.com/document/d/18pekFtO7mJzjpvvFsl45B9Z4x30UFErkff2tYLxTvmE/edit
Introduced 3 new impact ratings
- more-info-needed-promising
- too-rich
- slightly-low
Slightly-low is now mapped to Bronze and low is now mapped to Not Recommended.
This means charities that were previously displayed as Bronze will now display as Not Recommended.
Also, added labels to confidence values (high -> firm, medium -> tentative), deprecating low and very-low.
Co-authored-by: Anita W <anitawoodruff@users.noreply.github.com>
=> Update the impact ratings and confidence levels

src/js/C.js, src/js/components/SearchPage.jsx
As per the [new ratings system](https://docs.google.com/document/d/18pekFtO7mJzjpvvFsl45B9Z4x30UFErkff2tYLxTvmE/edit), this should be 'not recommended, too rich' in the editor, instead of 'do not donate'.
In search results it was displaying as "dubious impact", but spoke to Sanjay about this in our last meeting and he thinks it should be the same as what appears in the editor. So fixed this to use the editor label, same as the other ratings.
Here is a screenshot of what it looks like now in search results after editing a charity's impact to "not recommended, too rich", including hover text:
=> Change label to 'not recommended, too rich' for very-low impact

src/js/components/CharityPage.jsx
Ensuring the impact calculator doesn't appear on the charity page when the charity has no impact information available. 
E.g. for Hospice UK
@anitawoodruff
=> Remove impact calculator on charity page when impact is unavailable

src/js/C.js, src/js/components/MainDiv.jsx, src/style/main.less, src/style/positioning.less
This gets us quite a bit closer to the mocks, though there's still work to be done:
TODO in future PRs:
- Highlight links on hover (? - no mocks for this)
- Underline the selected page in blue to match mocks (if this is easy using CSS)
- Update which pages are linked to (to non-app pages) 
- HOME, ABOUT, CONTACT, and FAQ
- bit worried this will be complicated since code assumes they are all app pages right now, but haven't tried to actually change it yet
- Remove the account login dropdown (? see discussion points below)
- Add search widget to top-bar - Aishah might take this next time
- Align navbar links to the right hand side, against the search box (if easy with CSS)
=> Update navbar styling to be closer to mocks

src/js/components/SearchPage.jsx, src/style/SearchPage.less
Solution to this was to remove the placeholders completely and expand the column when a logo is unavailable. 
**How it looks now:**
The logo not showing due to a broken link will still be visible.
**How it looked before:**
@anitawoodruff
=> Fixing the text logo placeholder overflow

src/js/components/ImpactCalculator.jsx
Previously, after the user manually updated the impact calculator, the raw value they typed would always be displayed, regardless of pressing + / - buttons. You can observe this behaviour at test.sogive.org.
Now, the impact calculator behaves correctly - it updates based on both user input and increment/decrement buttons.
Unclear to me exactly how this change fixes it - I think it's something to do with this comment in PropControl.jsx: 
```
// What is rawValue?
// It is the value as typed by the user. This allows the user to move between invalid values, by keeping a copy of their raw input.
// NB: Most PropControl types ignore rawValue. Those that use it should display rawValue.
// Warning: rawValue === undefined/null means "use storeValue". BUT rawValue === "" means "show a blank"
```
=> Fix Impact Calculator bug

src/js/components/DonationWizard.jsx
We already hide the impact calculator on the CharityPage when noPublicDonations is true, and display the stated reason why. This change also hides the Donate Button, both from CharityPage and SearchResults.
=> Hide DonateButton when charity.noPublicDonations is true

src/java/org/sogive/server/SearchServlet.java
@winterstein I do not fully understand hows the relevance scores boosting works. It seems like each charity have a base score to scale with the `boost`? Anyway If we scale the boost value higher we can avoid the charity with lower impact tier rank on top of the searching result.
=> scale impact boost numbers

.project
- Whenever you open the `winterwell/sogive-app` directory in VSCode, then, if you have "Extension Pack for Java" installed, VSCode will generate these changes to the `.project` file that Eclipse also uses. 
- I couldn't find an explanation for why exactly it wants to ignore these resources, but it looks to me like sensible things to keep hidden when viewing in an IDE (node_module files, .git files, and files generated by the Java language server).
- I checked that the project still opens fine and runs from Eclipse with these changes. 
- An alternative would be to add `.project` to the `gitignore`, but then new contributors wouldn't be able to import directly as an Eclipse project.
=> Add filteredResources entry to .project file

src/js/components/MainDiv.jsx, src/js/components/SearchPage.jsx, src/style/main.less
Here is how it looks now:
Searching with it now works! :D it took me & @aissshah a lot of fiddling around, trying to understand PropControl and DataStore to get it to work.
I'm not super happy with it still, since the only way we got it working was to get rid of the 'Form' element and give the submit button a dynamically-generated anchor link which appends the query parameter. The lack of Form means that pressing 'enter' from the text box no longer works to perform the search. Also typing in it is quite laggy - and I couldn't use PropControl `fast` property because it wouldn't always get the up-to-date query parameter when pressing Search.
I think the solution may be to get rid of the PropControl and use a standard Input Text. Either that or stop using an anchor tag to make the button …
=> Display a search widget in the navigation bar

src/java/org/sogive/server/CharityServlet.java
@DanielRobertAppel This should fix the bug of not fetching redirected charity in portal.
=> fix error when noRedirect = null

src/js/components/AccountPage.jsx, src/js/components/GiftAidForm.jsx, src/js/components/ImpactCalculator.jsx, src/js/components/RegisterPage.jsx, src/js/components/SearchPage.jsx, src/js/components/editor/EditCharityPage.jsx, src/js/components/editor/EditFundRaiserPage.jsx, src/js/components/editor/EditorDashboardPage.jsx
- Cleaning up Webpack configs exposed a dependency loop between Misc.jsx and PropControl.jsx
- This is resolved by removing Misc.PropControl and Misc.FormControl from Misc.jsx in the wwappbase.js repo
- Before doing this, projects using wwappbase.js should stop invoking Misc.PropControl
=> Change all uses of Misc.PropControl to PropControl

production.server.project.builder.sh
Hello,
Much like #296, our production server is now running a newer version of NodeJS (16.x). This PR updates the version check in our production builder script accordingly.
Thanks,
Aidan
=> update nodejs check in production builder
