winterstein/sogive-app

- README.md
mention which version of elastic search and how to get it and run it
> README backend instruction improvements

- src/js/components/editor/EditCharityPage.jsx
- src/js/components/editor/SimpleEditCharityPage.jsx
Here are the small improvements which Sanjay requested.
> Charity Editor improvements

- README.md
- runtest.js
Hi Daniel! Thought it would be good to document how to run the tests somewhere.
Best,
Anita
> Add instructions for running puppeteer tests

- README.md
Have tested and this works on my Mac (OS 10.15.7 Catalina).
> Add Mac installation instructions to README

- src/js/components/DonationWizard.jsx
- think this crept in for testing purposes at https://github.com/winterstein/sogive-app/commit/479409591e08841dfcd3e6394fd95d2e92892992 but can be removed now
> Remove hourly repeat donation option

- README.md
Went through these with @aissshah just now and added in everything we needed to get the backend running on her laptop.
> Improve backend development instructions

- package.json
making the list of npm dependency packages harmonius.
> correcting package.json

- src/java/org/sogive/server/SearchServlet.java
- src/js/components/SearchPage.jsx
- src/js/plumbing/ServerIO.js
Note, this PR depends on https://github.com/good-loop/elasticsearch-java-client/pull/3 being merged to the elasticsearch-java-client repo first.
Probably easiest to review commit-by-commit because of the rename commit.
> Show all charities on home page and order by impact 

- src/style/colours.less
- src/style/footer.less
- web/index.html
These are the changes to update the footer to match the designs.
- added a new colour
- changed the html to include the new copy
- modified the footer.less file
Question:
Almost all of the values are hard-coded, which doesn't seem like the best way of doing things. Is there a suggestion for improvement?
Some lovely-sized screenshots:
(though you can see part of my panel in the desktop image)
Mobile: 
@anitawoodruff
> New footer designs

- src/js/components/MainDiv.jsx
- src/js/plumbing/ServerIO.js
- src/style/main.less
**Important: This PR depends on https://github.com/good-loop/wwappbase.js/pull/48 already being merged to wwappbase.js, which adds support for external links in the navbar**
- Removed links to dashboard, events & fundraisers
- Renamed 'search' to 'Home'
- stopped forcing lowercase styling from CSS
- Added links to 'About', 'Contact', 'FAQ' on sogive.org
- Made logo point to sogive.org
The above changes were agreed with Sarah
paired with @aissshah on these changes
> Update nav links to Home, About, Contact, FAQ

- src/js/components/LearnAboutRatings.jsx
Updating the text within the _learn about our ratings_ modal
@anitawoodruff
> update learn about our ratings text

- src/java/org/sogive/server/CharityServlet.java
- src/js/components/editor/EditCharityPage.jsx
- src/js/components/editor/SimpleEditCharityPage.jsx
- webpack.config.js
Code should work now, but the UI itself have have improvements (i.e. how to visually let user know they should not edit the page that have redirection).
> Feature/2021 aug/uieditor

- src/java/org/sogive/server/CharityServlet.java
- src/js/components/editor/EditCharityPage.jsx
- src/js/components/editor/SimpleEditCharityPage.jsx
Reckon I could use warning instead of just simple text
> UI improvements and better function for

- src/js/components/LearnAboutRatings.jsx
Used the description provided by Sarah
> Add description for 'More info needed (promising)' and make ratings bold in modal

- src/java/org/sogive/data/charity/Thing.java
- src/java/org/sogive/data/loader/Editorials.java
- src/java/org/sogive/data/loader/ImportOSCRData.java
- src/java/org/sogive/data/loader/JsoupDocumentFetcher.java
- src/java/org/sogive/server/CharityServlet.java
- src/js/components/editor/EditCharityPage.jsx
Well done Roscoe for tracking this bug down.
After looking at the usage of Thing, I believe the `"" = null` code was written so that csv imports wouldn't blank-out data. So I have adjusted the ImportOSCRData code.
> Feature/2021 08/fix saving redirect

- src/puppeteer-tests/SoGiveSelectors.js
- src/puppeteer-tests/__tests__/editor-dashboard.test.js
- src/puppeteer-tests/__tests__/editor.test.js
> Fix editor-dashboard & editor.test.js to work with new site design

- src/js/components/PrivacyPolicyPage.jsx
- src/js/components/TermsPage.jsx
- src/js/components/WebsiteCards.jsx
- src/style/WebsiteCards.less
- web/index.html
- web/js/form.js
- web/js/sogive.js
PS I still do not have the writing of FAQ
> Website revamp 2021

- src/js/components/WebsiteCards.jsx
- src/style/main.less
We might wanna keep this branch open for me to pull fixes
> NavItem Button Size

- src/js/components/HomePage.jsx
> faq updates

- src/js/components/CareersPage.jsx
- src/style/CareersPage.less
- src/style/main.less
Might want different pages for each job ads, but that's the design decision. We can push this first.
> add job ads Analyst

- src/js/components/CareersPage.jsx
> Volunteer Analysts

- src/js/components/CareersPage.jsx
- src/js/components/DonationWizard.jsx
@winterstein I will cherry pick the edits in CareersPage and leave the bug fixes to get tested in next release.
> Hotfix/2021 12/donationwizard currencyconvert

- src/js/plumbing/ServerIO.js
> Login Endpoint fix

- src/style/main.less
- src/style/navbar.less
Hello @winterstein,
This PR will fix the issue with the account dropdown section of the navbar floating off screen (seen at https://test.sogive.org).
- Aidan
> update navbar css

- src/js/components/HomePage.jsx
- src/js/components/MethodPage.jsx
> Feature/2022 03/hotfixes

- src/js/components/CharityPage.jsx
- src/js/plumbing/ServerIO.js
- src/style/fonts.less
- src/style/sogive-fonts.less
- web/index.html
regarding Website improvements - SoGive website: monday task
- tweaked font sizes
﻿- fixed policy footer
﻿- tweaked the charity page to be an example of what the charity page could look like by removing the second column. If this is roughly what SoGive is looking for then I can keep working on it, if not we could organize a wee meeting to talk about any potential changes.
> Feature/2022 08/font tweaks

- src/js/components/HomePage.jsx
- src/style/HomePage.less
Added warning that content might not be up to date as SoGives strategy changes. If we're looking for something different or want me to tweak this solution, then I'd be happy to provide
> Feature/2022 08/homepage sticker

- package.json
Hello @winterstein,
This should fix the build errors I keep receiving from the CI.
> add prismjs to deps to fix build error

- config/vdurkin-gl.js
- src/js/components/editor/EditCharityPage.jsx
- src/js/components/editor/SimpleEditCharityPage.jsx
Allow alternative logo uploads from sogive
> Alternative logo prop

- src/java/org/sogive/server/CharityServlet.java
Tested on local and it went well.
Need to merge and deploy https://github.com/good-loop/open-code/pull/77/ before we merge this.
> coverting id to @id
